Add content in README file for it's needed to publish on pypi
This change should fix error when publishing:

HTTPError: 400 Client Error: The description failed to render in the
default format of reStructuredText. See
https://test.pypi.org/help/#description-content-type for more
information. for url: https://test.pypi.org/legacy/

Change-Id: I4e8f9977ecfcc6ed102fe614ce8c54e3a8ee6105